/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { WaterLevel } from "../WaterLevel";

export class WaterLevel__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<WaterLevel> {
    return super.deploy(overrides || {}) as Promise<WaterLevel>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): WaterLevel {
    return super.attach(address) as WaterLevel;
  }
  connect(signer: Signer): WaterLevel__factory {
    return super.connect(signer) as WaterLevel__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WaterLevel {
    return new Contract(address, _abi, signerOrProvider) as WaterLevel;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "waterLevel",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060a18061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806383851b7214602d575b600080fd5b604760048036036020811015604157600080fd5b50356059565b60408051918252519081900360200190f35b6000602081905290815260409020548156fea2646970667358221220441b19d5650689e25753cd6327e28db08e979ced10d537a9d27c5e58bcd70bff64736f6c63430006060033";
