/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CurrentTimeMockInterface extends ethers.utils.Interface {
  functions: {
    "currentTime()": FunctionFragment;
    "timeTravel(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "currentTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeTravel",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timeTravel", data: BytesLike): Result;

  events: {};
}

export class CurrentTimeMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CurrentTimeMockInterface;

  functions: {
    currentTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    "currentTime()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    timeTravel(
      s: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "timeTravel(uint256)"(
      s: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  currentTime(overrides?: CallOverrides): Promise<BigNumber>;

  "currentTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  timeTravel(
    s: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "timeTravel(uint256)"(
    s: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    currentTime(overrides?: CallOverrides): Promise<BigNumber>;

    "currentTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    timeTravel(s: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "timeTravel(uint256)"(
      s: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    currentTime(overrides?: CallOverrides): Promise<BigNumber>;

    "currentTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    timeTravel(s: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "timeTravel(uint256)"(
      s: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    currentTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "currentTime()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timeTravel(
      s: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "timeTravel(uint256)"(
      s: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
